parameters:
    json_rpc_server: https://tanoconsulting.com/sw/jsonrpc/demo/server/server.php
    json_rpc_client_options: []

services:
    # explicitly configure the services where autowiring is impossible

    App\Service\JsonRpcClient:
        class: PhpXmlRpc\JsonRpc\Client
        arguments:
            - '%json_rpc_server%'
        calls:
            - setOptions: ['%json_rpc_client_options%']

    App\Controller\ClientController:
        arguments:
            $client: '@App\Service\JsonRpcClient'
            # in case you want to use a dedicated log file for all json-rpc related stuff
            #$logger: '@monolog.logger.jsonrpc'
